# Binaries
brew 'awscli'
brew 'bat'
brew 'eza'
brew 'fd'
brew 'fzf'
brew 'gh'
brew 'git-delta'
brew 'jq'
# brew 'mackup' # Disabled until https://github.com/lra/mackup?tab=readme-ov-file#warning is resolved
brew 'mas'
brew 'opencode'
brew 'ripgrep'
brew 'shellcheck'
brew 'spaceship'
brew 'zoxide'

# Spatie Medialibrary
brew 'jpegoptim'
brew 'optipng'
brew 'pngquant'
brew 'svgo'
brew 'gifsicle'
brew 'libavif'

# Apps
cask '1password'
cask 'adobe-creative-cloud'
cask 'chatgpt'
cask 'claude'
cask 'discord'
cask 'elgato-camera-hub'
cask 'elgato-control-center'
cask 'elgato-wave-link'
cask 'firefox'
cask 'ghostty'
cask 'github'
cask 'google-chrome'
cask 'herd'
cask 'iina'
cask 'jetbrains-toolbox'
cask 'logi-options+'
cask 'microsoft-edge'
cask 'microsoft-teams'
cask 'notion'
cask 'notion-calendar'
cask 'notion-mail'
cask 'opencode-desktop'
cask 'opera'
cask 'plexamp'
cask 'postman'
cask 'raycast'
cask 'readdle-spark'
cask 'runjs'
cask 'setapp'
cask 'spotify'
cask 'thebrowsercompany-dia'
cask 'tinkerwell'
cask 'visual-studio-code'
cask 'warp'
cask 'wispr-flow'

# QuickLook Plugins
cask 'betterzip'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'suspicious-package'
cask 'syntax-highlight'

# Fonts
cask 'font-fira-code-nerd-font'

# Mac App Store
mas "1Password for Safari", id: 1569813296
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
